---
- name: install httpd in s1 and s2
  hosts: all
  become: true

  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present

  - name: start service 
    service:
      name: httpd  
      state: started

  - name: copy files 
    copy:
      src: /home/ec2-user/index.html
      dest: /var/www/html/index.html